project: main.o add.o print.o delete.o reverse.o
	gcc -o project main.o add.o print.o delete.o reverse.o
reverse.o: reverse.c
	gcc -c reverse.c -o reverse.o
main.o: main.c
	gcc -c main.c -o main.o

add.o: add.c
	gcc -c add.c -o add.o
print.o: print.c
	gcc -c print.c -o print.o
delete.o: delete.c
	gcc -c delete.c -o delete.o
